export const statusList = ['interview', 'declined', 'pending', 'caca'];

export const oilsList = [
   '',
   'Abeto de Vancouver (Idaho Grand Fir)',
   'Albahaca (Basil)',
   'Alcanforero (Ravintsara)',
   'Alcaravea (Caraway)',
   'Angelica',
   'Árbol de té (Tea Tree)',
   'Bergamota (Bergamot)',
   'Canela (Cinnamon Bark)',
   'Cassia',
   'Cedro (Cedarwood)',
   'Ciprés (Cypress)',
   'Citronela (Citronella)',
   'Clavo (Clove)',
   'Copaiba',
   'Davana',
   'Dorado Azul',
   'Elemi',
   'Enebro (Juniper)',
   'Eneldo (Dill)',
   'Esclarea (Clary Sage)',
   'Eucalipto azul (Eucalyptus Blue)',
   'Eucalyptus Globulus',
   'Eucalyptus Radiata',
   'Gaulteria (Wintergreen)',
   'Geranio (Geranium)',
   'Geranium Bourbon',
   'Goldenrod',
   'Helicriso (Helichrysum)',
   'Hierbabuena (Spearmint)',
   'Hinojo (Fennel)',
   'Hinoki',
   'Hong',
   'Incienso (Frankincense)',
   'Incienso sagrado (Sacred Frankincense)',
   'Jara (Cistus)',
   'Jazmín (Jasmine)',
   'Jengibre (Ginger)',
   'Kunzea',
   'Lavanda (Lavender)',
   'Ledum',
   'Lima (Lime)',
   'Limón (Lemon)',
   'Limón de jade (Jade Lemon)',
   'Mandarina (Tangerine)',
   'Manzanilla (Roman Chamomile)',
   'Matricaria (German',
   'Mejorana (Marjoram)',
   'Melisa (Melissa)',
   'Menta (Peppermint)',
   'Mirra (Myrrh)',
   'Mirto (Myrtle)',
   'Mirto ',
   'Mirto limón (Lemon Myrtle)',
   'Naranja (Orange)',
   'Neroli',
   'Nuez moscada (Nutmeg)',
   'Ocotea',
   'Orégano (Oregano)',
   'Pachulí (Patchouli)',
   'Palo Santo',
   'Pasto de limón (Lemongrass)',
   'Peppermint Essential Oil Sample',
   'Pícea azul de Idaho (Idaho Blue Spruce)',
   'Pícea negra Northern Lights (Northern Lights Black Spruce)',
   'Pimienta negra (Black Pepper)',
   'Pino (Pine)',
   'Pomelo (Grapefruit)',
   'Romero (Rosemary)',
   'Rosa (Rose)',
   'Rue',
   'Salvia (Sage)',
   'Sándalo Real Hawaiano (Royal Hawaiian Sandalwood)^',
   'Sándalo sagrado (Sacred Sandalwood)',
   'Semilla de zahahoria (Carrot Seed)',
   'Tanaceto azul (Blue Tansy)',
   'Thieves Essential Oil Sample',
   'Tomillo (Thyme)',
   'Vainilla (Vanilla)',
   'Valeriana (Valerian)',
   'Vetiver',
   'Xiang Mao',
   'Ylang Ylang',
];

/////////////////////
////////////////////
// [
// 'Abeto de Vancouver (Idaho Grand Fir)',
// 'Albahaca (Basil)',
// 'Alcanforero (Ravintsara)',
// 'Alcaravea (Caraway)',
// 'Angelica',
// 'Árbol de té (Tea Tree)',
// 'Bergamota (Bergamot)',
// 'Canela (Cinnamon Bark)',
// 'Cassia',
// 'Cedro (Cedarwood)',
// 'Ciprés (Cypress)',
// 'Citronela (Citronella)',
// 'Clavo (Clove)',
// 'Copaiba',
// 'Davana',
// 'Dorado Azul',
// 'Elemi',
// 'Enebro (Juniper)',
// 'Eneldo (Dill)',
// 'Esclarea (Clary Sage)',
// 'Eucalipto azul (Eucalyptus Blue)',
// 'Eucalyptus Globulus',
// 'Eucalyptus Radiata',
// 'Gaulteria (Wintergreen)',
// 'Geranio (Geranium)',
// 'Geranium Bourbon',
// 'Goldenrod',
// 'Helicriso (Helichrysum)',
// 'Hierbabuena (Spearmint)',
// 'Hinojo (Fennel)',
// 'Hinoki',
// 'Hong',
// 'Incienso (Frankincense)',
// 'Incienso sagrado (Sacred Frankincense)',
// 'Jara (Cistus)',
// 'Jazmín (Jasmine)',
// 'Jengibre (Ginger)',
// 'Kunzea',
// 'Lavanda (Lavender)',
// 'Ledum',
// 'Lima (Lime)',
// 'Limón (Lemon)',
// 'Limón de jade (Jade Lemon)',
// 'Mandarina (Tangerine)',
// 'Manzanilla (Roman Chamomile)',
// 'Matricaria (German',
// 'Mejorana (Marjoram)',
// 'Melisa (Melissa)',
// 'Menta (Peppermint)',
// 'Mirra (Myrrh)',
// 'Mirto (Myrtle)',
// 'Mirto ',
// 'Mirto limón (Lemon Myrtle)',
// 'Naranja (Orange)',
// 'Neroli',
// 'Nuez moscada (Nutmeg)',
// 'Ocotea',
// 'Orégano (Oregano)',
// 'Pachulí (Patchouli)',
// 'Palo Santo',
// 'Pasto de limón (Lemongrass)',
// 'Peppermint Essential Oil Sample',
// 'Pícea azul de Idaho (Idaho Blue Spruce)',
// 'Pícea negra Northern Lights (Northern Lights Black Spruce)',
// 'Pimienta negra (Black Pepper)',
// 'Pino (Pine)',
// 'Pomelo (Grapefruit)',
// 'Romero (Rosemary)',
// 'Rosa (Rose)',
// 'Rue',
// 'Salvia (Sage)',
// 'Sándalo Real Hawaiano (Royal Hawaiian Sandalwood)^',
// 'Sándalo sagrado (Sacred Sandalwood)',
// 'Semilla de zahahoria (Carrot Seed)',
// 'Tanaceto azul (Blue Tansy)',
// 'Thieves Essential Oil Sample',
// 'Tomillo (Thyme)',
// 'Vainilla (Vanilla)',
// 'Valeriana (Valerian)',
// 'Vetiver',
// 'Xiang Mao',
// 'Ylang Ylang',
// ]
/////////////////////
//////////////////////
////////////////////

// Abeto de Vancouver (Idaho Grand Fir),Albahaca (Basil),Alcanforero (Ravintsara),Alcaravea (Caraway),Angelica,Árbol de té (Tea Tree),Bergamota (Bergamot),Canela (Cinnamon Bark),Cassia,Cedro (Cedarwood),Ciprés (Cypress),Citronela (Citronella),Clavo (Clove),Copaiba,Davana,Dorado Azul,Elemi,Enebro (Juniper),Eneldo (Dill),Esclarea (Clary Sage),Eucalipto azul (Eucalyptus Blue),Eucalyptus Globulus,Eucalyptus Radiata,Gaulteria (Wintergreen),Geranio (Geranium),Geranium Bourbon,Goldenrod,Helicriso (Helichrysum),Hierbabuena (Spearmint),Hinojo (Fennel),Hinoki,Hong,Incienso (Frankincense),Incienso sagrado (Sacred Frankincense),Jara (Cistus),Jazmín (Jasmine),Jengibre (Ginger),Kunzea,Lavanda (Lavender),Ledum,Lima (Lime),Limón (Lemon),Limón de jade (Jade Lemon),Mandarina (Tangerine),Manzanilla (Roman Chamomile),Matricaria (German,Mejorana (Marjoram),Melisa (Melissa),Menta (Peppermint),Mirra (Myrrh),Mirto (Myrtle),Mirto ,Mirto limón (Lemon Myrtle),Naranja (Orange),Neroli,Nuez moscada (Nutmeg),Ocotea,Orégano (Oregano),Pachulí (Patchouli),Palo Santo,Pasto de limón (Lemongrass),Peppermint Essential Oil Sample,Pícea azul de Idaho (Idaho Blue Spruce),Pícea negra Northern Lights (Northern Lights Black Spruce),Pimienta negra (Black Pepper),Pino (Pine),Pomelo (Grapefruit),Romero (Rosemary),Rosa (Rose),Rue,Salvia (Sage),Sándalo Real Hawaiano (Royal Hawaiian Sandalwood)^,Sándalo sagrado (Sacred Sandalwood),Semilla de zahahoria (Carrot Seed),Tanaceto azul (Blue Tansy),Thieves Essential Oil Sample,Tomillo (Thyme),Vainilla (Vanilla),Valeriana (Valerian),Vetiver,Xiang Mao,Ylang Ylang

// Neuralgia, Cólico, Parto, Migraña, Dolor de muelas, Quemaduras, Ciática, Dolor de cabeza, fiebre, torcedura

// Dolor de cabeza
// Neuralgia
// Cólico
// torcedura
// Dolor de muelas
// Quemaduras
// Parto
// fiebre
// Migraña
// Ciática

/////////////////////
//////////////////////
////////////////////

// "Abeto de Vancouver (Idaho Grand Fir)","Albahaca (Basil)","Alcanforero (Ravintsara)","Alcaravea (Caraway)","Angelica","Árbol de té (Tea Tree)","Bergamota (Bergamot)","Canela (Cinnamon Bark)","Cassia","Cedro (Cedarwood)","Ciprés (Cypress)","Citronela (Citronella)","Clavo (Clove)","Copaiba","Davana","Dorado Azul","Elemi","Enebro (Juniper)","Eneldo (Dill)","Esclarea (Clary Sage)","Eucalipto azul (Eucalyptus Blue)","Eucalyptus Globulus","Eucalyptus Radiata","Gaulteria (Wintergreen)","Geranio (Geranium)","Geranium Bourbon","Goldenrod","Helicriso (Helichrysum)","Hierbabuena (Spearmint)","Hinojo (Fennel)","Hinoki","Hong","Incienso (Frankincense)","Incienso sagrado (Sacred Frankincense)","Jara (Cistus)","Jazmín (Jasmine)","Jengibre (Ginger)","Kunzea","Lavanda (Lavender)","Ledum","Lima (Lime)","Limón (Lemon)","Limón de jade (Jade Lemon)","Mandarina (Tangerine)","Manzanilla (Roman Chamomile)","Matricaria (German","Mejorana (Marjoram)","Melisa (Melissa)","Menta (Peppermint)","Mirra (Myrrh)","Mirto (Myrtle)","Mirto ","Mirto limón (Lemon Myrtle)","Naranja (Orange)","Neroli","Nuez moscada (Nutmeg)","Ocotea","Orégano (Oregano)","Pachulí (Patchouli)","Palo Santo","Pasto de limón (Lemongrass)","Peppermint Essential Oil Sample","Pícea azul de Idaho (Idaho Blue Spruce)","Pícea negra Northern Lights (Northern Lights Black Spruce)","Pimienta negra (Black Pepper)","Pino (Pine)","Pomelo (Grapefruit)","Romero (Rosemary)","Rosa (Rose)","Rue","Salvia (Sage)","Sándalo Real Hawaiano (Royal Hawaiian Sandalwood)","Sándalo sagrado (Sacred Sandalwood)","Semilla de zahahoria (Carrot Seed)","Tanaceto azul (Blue Tansy)","Thieves Essential Oil Sample","Tomillo (Thyme)","Vainilla (Vanilla)","Valeriana (Valerian)","Vetiver","Xiang Mao","Ylang Ylang"

// "Neuralgia","Cólico","Parto","Migraña","Dolor de muelas","Quemaduras","Ciática","Dolor de cabeza","fiebre","torcedura"
